info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: 
  routes:
    customer: 
      path: /customer/**
      serviceId: MsCustomer
 
    product: 
      path: /product/**
      serviceId: MsProduct   

    sale: 
      path: /sale/**
      serviceId: TesteSale
    
    auth:
      path: /auth/**
      serviceId: MsAuthentication
    
    newsl:
      path: /newsl/**
      serviceId: MsNewsletter


ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
